# Generated by Django 4.2.6 on 2025-06-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('logo', models.FileField(upload_to='client_files/logos/', verbose_name='Logo')),
                ('banner', models.FileField(upload_to='client_files/banners/', verbose_name='Banner')),
                ('icons', models.FileField(upload_to='client_files/icons/', verbose_name='Iconos')),
                ('images', models.FileField(upload_to='client_files/images/', verbose_name='Imágenes')),
                ('videos', models.FileField(upload_to='client_files/videos/', verbose_name='Videos')),
                ('additional_resources', models.TextField(verbose_name='Recursos Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Diseño Web',
                'verbose_name_plural': 'Solicitudes de Diseño Web',
            },
        ),
    ]
