# Generated by Django 4.2.6 on 2025-06-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0002_remove_old_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('logo', 'Logo'), ('banner', 'Banner'), ('icons', 'Iconos'), ('images', 'Imágenes'), ('videos', 'Videos')], max_length=10)),
                ('file', models.FileField(upload_to='client_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='post_form.webdesignrequest')),
            ],
            options={
                'verbose_name': 'Archivo de Diseño Web',
                'verbose_name_plural': 'Archivos de Diseño Web',
            },
        ),
    ]
