# Generated by Django 4.2.6 on 2025-06-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0003_webdesignfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesignrequest',
            name='additional_resources',
            field=models.TextField(blank=True, null=True, verbose_name='Recursos Adicionales'),
        ),
    ]
