# Generated by Django 4.2.6 on 2025-06-06 18:17

from django.db import migrations, models
import post_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0004_alter_webdesignrequest_additional_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesignfile',
            name='file',
            field=models.FileField(upload_to=post_form.models.get_upload_path),
        ),
    ]
