# Generated by Django 4.2.6 on 2025-06-06 18:24

from django.db import migrations, models
import post_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0005_alter_webdesignfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesignfile',
            name='file',
            field=models.FileField(help_text='Tamaños máximos: Videos (50MB), Imágenes (10MB), Iconos (5MB)', upload_to=post_form.models.get_upload_path, validators=[post_form.models.validate_file_size]),
        ),
    ]
