# Generated by Django 4.2.6 on 2025-06-06 18:28

from django.db import migrations, models
import post_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0006_alter_webdesignfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesignfile',
            name='file',
            field=models.FileField(help_text='Tamaños máximos: Videos (500MB), Imágenes (100MB), Iconos (50MB)', upload_to=post_form.models.get_upload_path, validators=[post_form.models.validate_file_size]),
        ),
    ]
