# Generated by Django 4.2.6 on 2025-06-06 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import post_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0007_alter_webdesignfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('additional_resources', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='webdesignfile',
            options={'verbose_name': 'Web Design File', 'verbose_name_plural': 'Web Design Files'},
        ),
        migrations.AlterModelOptions(
            name='webdesignrequest',
            options={'verbose_name': 'Web Design Request', 'verbose_name_plural': 'Web Design Requests'},
        ),
        migrations.AlterField(
            model_name='webdesignfile',
            name='file',
            field=models.FileField(blank=True, help_text='Maximum sizes: Videos (500MB), Images (100MB), Icons (50MB)', null=True, upload_to=post_form.models.get_upload_path, validators=[post_form.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='webdesignfile',
            name='file_type',
            field=models.CharField(choices=[('logo', 'Logo'), ('banner', 'Banner'), ('icons', 'Icons'), ('images', 'Images'), ('videos', 'Videos')], max_length=10),
        ),
        migrations.AlterField(
            model_name='webdesignrequest',
            name='additional_resources',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Resources'),
        ),
        migrations.AlterField(
            model_name='webdesignrequest',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Client Name'),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=post_form.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'mp4', 'webm']), post_form.models.validate_file_size])),
                ('file_type', models.CharField(choices=[('logo', 'Logo'), ('banner', 'Banner'), ('icons', 'Icons'), ('images', 'Images'), ('videos', 'Videos')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='post_form.clientrequest')),
            ],
        ),
    ]
