# Generated by Django 4.2.6 on 2025-06-06 21:49

from django.db import migrations, models
import post_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0008_clientrequest_alter_webdesignfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'verbose_name': 'File Upload', 'verbose_name_plural': 'File Uploads'},
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file upload', null=True, upload_to=post_form.models.get_upload_path),
        ),
    ]
