# Generated by Django 4.2.6 on 2025-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0009_alter_fileupload_options_alter_fileupload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='request',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/additional/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/banners/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/logos/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
