# Generated by Django 4.2.6 on 2025-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_form', '0010_rename_uploaded_at_fileupload_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/backgrounds/'),
        ),
    ]
